#!/usr/bin/env python3
"""
Require Linux restricted-mode validation evidence before M3 promotion.
"""
from __future__ import annotations

import argparse
import os
import platform
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def _write_report(path: Path, bot_name: str, lines: list[str], passed: bool) -> None:
    text: list[str] = []
    text.append("# M3 Linux restricted-mode readiness report")
    text.append("")
    text.append("Generated by `workflows/m3_linux_restricted_gate.py`.")
    text.append("")
    text.append("## Summary")
    text.append(f"- Bot: `{bot_name}`")
    text.append(f"- Host platform: `{platform.system()}`")
    text.append("- Gate requirement: Linux host + `validate_submission(..., limit_resources=True)` success.")
    text.append("")
    text.append("## Evidence")
    for line in lines:
        text.append(f"- {line}")
    text.append("")
    text.append("- Overall status: **PASS**" if passed else "- Overall status: **FAIL**")
    text.append("")
    path.write_text("\n".join(text), encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--bot-name", default="Yolanda")
    parser.add_argument("--write-md", default="docs/m3_linux_restricted_readiness.md")
    parser.add_argument(
        "--enforce-linux",
        action=argparse.BooleanOptionalAction,
        default=True,
        help="Fail on non-Linux hosts to prevent promotion without restricted-mode evidence.",
    )
    args = parser.parse_args()

    report_path = Path(args.write_md)
    if not report_path.is_absolute():
        report_path = ROOT / report_path

    evidence: list[str] = []
    passed = True
    if platform.system() != "Linux":
        evidence.append("non_linux_host_detected")
        evidence.append("restricted_mode_not_executed")
        passed = False
        _write_report(report_path, args.bot_name, evidence, passed)
        print(f"Wrote {report_path}")
        if args.enforce_linux:
            print("FAIL: Linux restricted-mode gate requires execution on Linux host.")
            return 1
        return 0

    sys.path.insert(0, str(ROOT / "engine"))
    try:
        import gameplay
    except Exception as exc:  # pragma: no cover - import failure should be fatal in workflow usage.
        evidence.append(f"engine_import_error={exc}")
        _write_report(report_path, args.bot_name, evidence, False)
        print(f"Wrote {report_path}")
        print(f"FAIL: unable to import gameplay: {exc}")
        return 1

    ok, message = gameplay.validate_submission(
        os.path.join(os.getcwd(), "3600-agents"),
        args.bot_name,
        limit_resources=True,
        use_gpu=False,
    )
    evidence.append(f"validate_submission_ok={bool(ok)}")
    evidence.append(f"validate_submission_message={message!r}")
    passed = bool(ok)
    _write_report(report_path, args.bot_name, evidence, passed)
    print(f"Wrote {report_path}")
    if not passed:
        print("FAIL: Linux restricted-mode validate_submission returned False.")
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
