#!/usr/bin/env python3
"""
Generate explicit M3 mandatory scenario coverage report.
"""
from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


@dataclass
class ScenarioCheck:
    scenario: str
    status: str  # PASS / FAIL
    evidence: str


def _file_text(path: Path) -> str:
    return path.read_text(encoding="utf-8", errors="ignore") if path.exists() else ""


def _has_patterns(path: Path, patterns: list[str]) -> bool:
    text = _file_text(path)
    return all(p in text for p in patterns)


def _report_has_pass(path: Path) -> bool:
    if not path.exists():
        return False
    text = _file_text(path)
    return "- Overall status: **PASS**" in text


def main() -> int:
    checks: list[ScenarioCheck] = []

    # 1) Search generation default + explicit inclusion
    s1_ok = _has_patterns(
        ROOT / "tests" / "test_discrepancy_contract.py",
        ["test_board_default_move_generation_excludes_search"],
    ) and _has_patterns(
        ROOT / "tests" / "test_policy_contract.py",
        ["test_explicit_search_candidates_are_present"],
    )
    checks.append(
        ScenarioCheck(
            scenario="Search generation default and explicit inclusion path",
            status="PASS" if s1_ok else "FAIL",
            evidence="tests/test_discrepancy_contract.py + tests/test_policy_contract.py",
        )
    )

    # 2) Tri-state search tuple parsing
    s2_ok = _has_patterns(
        ROOT / "tests" / "test_policy_contract.py",
        ["test_parse_search_tuple_tristate", "test_apply_search_channels_obeys_tri_state_and_deduplicates"],
    )
    checks.append(
        ScenarioCheck(
            scenario="Tri-state search tuple parsing",
            status="PASS" if s2_ok else "FAIL",
            evidence="tests/test_policy_contract.py",
        )
    )

    # 3) Search scoring + respawn parity
    s3_ok = _has_patterns(
        ROOT / "tests" / "test_discrepancy_contract.py",
        ["test_search_scoring_not_applied_in_board_apply_move"],
    ) and _has_patterns(
        ROOT / "tests" / "test_belief_engine.py",
        ["test_reset_prior_parity_non_identity_transition", "test_true_search_feedback_matches_reset_prior"],
    )
    checks.append(
        ScenarioCheck(
            scenario="Search scoring/respawn parity",
            status="PASS" if s3_ok else "FAIL",
            evidence="tests/test_discrepancy_contract.py + tests/test_belief_engine.py",
        )
    )

    # 4) Timeout edge handling + constructor/play budget windows
    s4_ok = _has_patterns(
        ROOT / "tests" / "test_time_manager.py",
        ["test_allocation_enters_emergency_near_floor", "test_t_eff_zero_triggers_emergency"],
    ) and _has_patterns(
        ROOT / "tests" / "test_agent_contract.py",
        ["test_constructor_reads_constructor_budget_time_left"],
    )
    checks.append(
        ScenarioCheck(
            scenario="Timeout edge handling and constructor/play budget windows",
            status="PASS" if s4_ok else "FAIL",
            evidence="tests/test_time_manager.py + tests/test_agent_contract.py",
        )
    )

    # 5) Linux restricted-mode readiness is mandatory before promotion.
    restricted_report = ROOT / "docs/m3_linux_restricted_readiness.md"
    s5_ok = _report_has_pass(restricted_report)
    s5_status = "PASS" if s5_ok else "FAIL"
    s5_evidence = (
        "docs/m3_linux_restricted_readiness.md reports PASS"
        if s5_ok
        else "Missing PASS in m3_linux_restricted_readiness.md (Linux restricted gate not satisfied)"
    )
    checks.append(
        ScenarioCheck(
            scenario="Local unrestricted vs restricted readiness checks",
            status=s5_status,
            evidence=s5_evidence,
        )
    )

    # 6) Reference-bot gates or proxy fallback with mandatory platform confirmation
    m2_logs = sorted((ROOT / "M2_match_results").glob("*.json"))
    s6_ok = len(m2_logs) >= 3
    checks.append(
        ScenarioCheck(
            scenario="Reference-bot gates / proxy fallback + platform confirmation requirement",
            status="PASS" if s6_ok else "FAIL",
            evidence=(
                "M2_match_results/*.json present (proxy evidence); final platform confirmation still required"
                if s6_ok
                else "Missing M2_match_results proxy evidence files"
            ),
        )
    )

    out_path = ROOT / "docs/m3_mandatory_scenario_coverage.md"
    lines: list[str] = []
    lines.append("# M3 mandatory scenario coverage")
    lines.append("")
    lines.append("Generated by `workflows/m3_scenario_coverage.py`.")
    lines.append("")
    lines.append("| Scenario | Status | Evidence |")
    lines.append("| --- | --- | --- |")
    for c in checks:
        lines.append(f"| {c.scenario} | {c.status} | {c.evidence} |")
    lines.append("")

    fail_count = sum(1 for c in checks if c.status == "FAIL")
    lines.append(f"- FAIL count: `{fail_count}`")
    if fail_count == 0:
        lines.append("- Overall status: **PASS**")
    else:
        lines.append("- Overall status: **FAIL**")
    lines.append("")
    out_path.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {out_path}")

    return 0 if fail_count == 0 else 1


if __name__ == "__main__":
    raise SystemExit(main())
