#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && cd .. && pwd)"
VENV_DIR="${ROOT_DIR}/.venv"
PYTHON="${VENV_DIR}/bin/python"

if [[ ! -x "${PYTHON}" ]]; then
  echo "ERROR: expected venv at ${VENV_DIR}; run validate_m0.sh first or create .venv"
  exit 2
fi

export PYTHONPATH="${ROOT_DIR}/engine:${ROOT_DIR}/3600-agents"
PROMOTION_GAMES="${PROMOTION_GAMES:-80}"
PROMOTION_SEED_BLOCKS="${PROMOTION_SEED_BLOCKS:-0 100 200}"
PROMOTION_PROFILE="${PROMOTION_PROFILE:-strict}"
PROMOTION_MD="${ROOT_DIR}/docs/m3_elo_uplift_vs_m2_baseline.md"
ABLATION_GAMES="${ABLATION_GAMES:-40}"
ABLATION_SEED_START="${ABLATION_SEED_START:-42}"
ENFORCE_LINUX_RESTRICTED="${ENFORCE_LINUX_RESTRICTED:-1}"
ENFORCE_SUBMISSION_INTEGRITY="${ENFORCE_SUBMISSION_INTEGRITY:-1}"
SUBMISSION_SMOKE_GAMES="${SUBMISSION_SMOKE_GAMES:-2}"
SUBMISSION_ZIP_PATH="${SUBMISSION_ZIP_PATH:-}"

echo "=== M3: unittest ==="
"${PYTHON}" -m unittest discover -s tests -p 'test_*.py' -v

echo "=== M3: adaptation clamp report ==="
"${PYTHON}" workflows/m3_generate_reports.py

echo "=== M3: quality_guard ==="
"${PYTHON}" workflows/quality_guard.py

echo "=== M3: Linux restricted-mode promotion gate ==="
if [[ "${ENFORCE_LINUX_RESTRICTED}" == "0" ]]; then
  "${PYTHON}" workflows/m3_linux_restricted_gate.py \
    --bot-name Yolanda \
    --write-md "${ROOT_DIR}/docs/m3_linux_restricted_readiness.md" \
    --no-enforce-linux
else
  "${PYTHON}" workflows/m3_linux_restricted_gate.py \
    --bot-name Yolanda \
    --write-md "${ROOT_DIR}/docs/m3_linux_restricted_readiness.md" \
    --enforce-linux
fi

echo "=== M3: submission integrity (zip parity + packaged smoke replay) ==="
submission_cmd=(
  "${PYTHON}" workflows/m3_submission_integrity.py
  --bot-name Yolanda
  --smoke-games "${SUBMISSION_SMOKE_GAMES}"
  --write-md "${ROOT_DIR}/docs/m3_submission_integrity_report.md"
)
if [[ -n "${SUBMISSION_ZIP_PATH}" ]]; then
  submission_cmd+=(--zip-path "${SUBMISSION_ZIP_PATH}")
fi
if [[ "${ENFORCE_SUBMISSION_INTEGRITY}" == "0" ]]; then
  submission_cmd+=(--no-enforce)
else
  submission_cmd+=(--enforce)
fi
"${submission_cmd[@]}"

echo "=== M3: mandatory scenario coverage matrix ==="
"${PYTHON}" workflows/m3_scenario_coverage.py

echo "=== M3: ablation matrix (opponent model / adaptive margin toggles) ==="
"${PYTHON}" workflows/m3_ablation_matrix.py \
  --games "${ABLATION_GAMES}" \
  --seed-start "${ABLATION_SEED_START}" \
  --profile "${PROMOTION_PROFILE}" \
  --write-md "${ROOT_DIR}/docs/m3_ablation_matrix_report.md" \
  --enforce

echo "=== M3: promotion-grade competitive gate (strict, multi-seed, high-sample) ==="
echo "profile=${PROMOTION_PROFILE} games_per_seed=${PROMOTION_GAMES} seeds='${PROMOTION_SEED_BLOCKS}'"

tmp_summary="$(mktemp)"
{
  echo "# M3 Elo uplift vs M2 baseline"
  echo
  echo "Generated by \`validate_m3.sh\` promotion gate."
  echo
  echo "- Profile: \`${PROMOTION_PROFILE}\`"
  echo "- Games per seed block: \`${PROMOTION_GAMES}\`"
  echo "- Seed blocks: \`${PROMOTION_SEED_BLOCKS}\`"
  echo "- Promotion gate: each block must pass enforced M3-vs-M2 gate"
  echo
} > "${tmp_summary}"

for seed in ${PROMOTION_SEED_BLOCKS}; do
  echo "--- seed_start=${seed} ---"
  block_log="$(mktemp)"
  if "${PYTHON}" workflows/m3_competitive_batch.py \
    --games "${PROMOTION_GAMES}" \
    --quiet \
    --profile "${PROMOTION_PROFILE}" \
    --seed-start "${seed}" \
    --min-games-for-gate "${PROMOTION_GAMES}" \
    --enforce-promotion-gate >"${block_log}" 2>&1; then
    cat "${block_log}"
  else
    cat "${block_log}"
    {
      echo "## Seed block ${seed}"
      echo
      echo '```'
      cat "${block_log}"
      echo '```'
      echo
    } >> "${tmp_summary}"
    rm -f "${block_log}"
    cp "${tmp_summary}" "${PROMOTION_MD}"
    echo "ERROR: M3 promotion gate failed for seed_start=${seed}"
    exit 1
  fi

  {
    echo "## Seed block ${seed}"
    echo
    echo '```'
    cat "${block_log}"
    echo '```'
    echo
  } >> "${tmp_summary}"
  rm -f "${block_log}"
done

cp "${tmp_summary}" "${PROMOTION_MD}"
rm -f "${tmp_summary}"

if [[ ! -f "${ROOT_DIR}/docs/m3_adaptation_clamp_verification_report.md" ]]; then
  echo "ERROR: missing m3_adaptation_clamp_verification_report.md"
  exit 1
fi
if [[ ! -f "${ROOT_DIR}/docs/m3_elo_uplift_vs_m2_baseline.md" ]]; then
  echo "ERROR: missing m3_elo_uplift_vs_m2_baseline.md"
  exit 1
fi
if [[ ! -f "${ROOT_DIR}/docs/m3_ablation_matrix_report.md" ]]; then
  echo "ERROR: missing m3_ablation_matrix_report.md"
  exit 1
fi
if [[ ! -f "${ROOT_DIR}/docs/m3_mandatory_scenario_coverage.md" ]]; then
  echo "ERROR: missing m3_mandatory_scenario_coverage.md"
  exit 1
fi
if [[ ! -f "${ROOT_DIR}/docs/m3_submission_integrity_report.md" ]]; then
  echo "ERROR: missing m3_submission_integrity_report.md"
  exit 1
fi
if [[ ! -f "${ROOT_DIR}/docs/m3_linux_restricted_readiness.md" ]]; then
  echo "ERROR: missing m3_linux_restricted_readiness.md"
  exit 1
fi

echo "validate_m3.sh completed successfully."
